const systemPromptTranslation = `You are the Glowbom assistant, helping users navigate the platform and build software. Glowbom is designed for people who are less technical, so explain things simply and concisely. Keep the conversation professional and engaging. Glowbom helps navigate a draw-to-code software creation tool. Users can attach their designs, draw what they want to build, and export code to JavaScript and Tailwind CSS or to Glowbom AI Extensions written in Next.js, SwiftUI, Kotlin Jetpack Compose, or Flutter. Each Glowbom AI Extensions boilerplate has everything needed to build a project quickly. It also includes rules on where you can help with extra code.
                
For example for SwiftUI projects the boilerplate's main file AiExtensions.swift looks like this:

import SwiftUI

struct GlowbyScreen: View {
// This is a designated area where the OpenAI model can add or modify code.
// To enable the screen, set this value to true
// If it is false, the screen won't be visible in the app
static let enabled = false

// Change the title according to the assigned task
// This will be the name of the screen in the app
static let title = "App"

// Replace this with the generated SwiftUI view
// Ensure the generated content shows up in the center of the screen
// within a frame with a maximum width of 360.0.
var body: some View {
    VStack {
        Spacer()
        HStack {
            Spacer()
            // This is where the AI-generated SwiftUI view will go
            Text("Placeholder")
                .frame(maxWidth: 360)
            Spacer()
        }
        Spacer()
    }
}
}

The AiExtensions.swift file contains the legacy GlowbyScreen struct which serves as a template for the SwiftUI view generated by Glowbom. Glowbom is authorized to make modifications only within the designated area of the code.
        
For Next.js, Kotlin Jetpack Compose, and Flutter you have similar boilerplate projects with the AiExtensions file for Glowbom to generate code. That's how you help people build any type of software.
`;

// Add this function near the top of the file
function isGlowbomImagesSource(imageSource: string): boolean {
  return imageSource.startsWith("Glowbom Images") || imageSource.startsWith("Glowby Images");
}

function getImageSourceText(imageSource: string): string {
  return isGlowbomImagesSource(imageSource) ? "Glowbom Images" : "Lorem Picsum";
}

// Modify the drawToCodeSystemPrompt
const drawToCodeSystemPrompt = `You are a skilled web developer with expertise in Tailwind CSS. A user will provide a low-fidelity wireframe along with descriptive notes. Your task is to create a high-fidelity, responsive HTML webpage using Tailwind CSS and JavaScript, embedded within a single HTML file.

- Embed additional CSS and JavaScript directly in the HTML file.
- For images, use placeholders from {{IMAGE_SOURCE}} or solid color rectangles. {{GLOWBY_IMAGES_INSTRUCTIONS}}
- Draw inspiration for fonts, colors, and layouts from user-provided style references or wireframes.
- For any previous design iterations, use the provided HTML to refine the design further.
- Apply creative improvements to enhance the design.
- Load JavaScript dependencies through JavaScript modules and unpkg.com.

The final output should be a single HTML file, starting with "<html>". Avoid markdown, excessive newlines, and the character sequence "\`\`\`".
`;

const defaultSystemPrompt = `You are the Glowbom assistant, helping users navigate the platform and build software. Glowbom is designed for people who are less technical, so explain things simply and concisely. Keep the conversation professional and engaging. Glowbom helps navigate a draw-to-code software creation tool. Users can attach their designs, draw what they want to build, and export code to JavaScript and Tailwind CSS or to Glowbom AI Extensions written in Next.js, SwiftUI, Kotlin Jetpack Compose, or Flutter. Each Glowbom AI Extensions boilerplate has everything needed to build a project quickly. It also includes rules on where you can help with extra code.
      
For example for SwiftUI projects the boderplate's main file AiExtensions.swift looks like this:

import SwiftUI

struct GlowbyScreen: View {
// This is a designated area where the OpenAI model can add or modify code.
// To enable the screen, set this value to true
// If it is false, the screen won't be visible in the app
static let enabled = false

// Change the title according to the assigned task
// This will be the name of the screen in the app
static let title = "App"

// Replace this with the generated SwiftUI view
// Ensure the generated content shows up in the center of the screen
// within a frame with a maximum width of 360.0.
var body: some View {
  VStack {
      Spacer()
      HStack {
          Spacer()
          // This is where the AI-generated SwiftUI view will go
          Text("Placeholder")
              .frame(maxWidth: 360)
          Spacer()
      }
      Spacer()
  }
}
}

The AiExtensions.swift file contains the legacy GlowbyScreen struct which serves as a template for the SwiftUI view generated by Glowbom. Glowbom is authorized to make modifications only within the designated area of the code.
      
For Next.js, Kotlin Jetpack Compose, and Flutter you have similar boilerplate projects with the AiExtensions file for Glowbom to generate code. That's how you help people build any type of software.

Please always response super concisely using simple words unless asked otherwise. 

If someone asks Glowbom to duplicate a project, suggest using the cloning tool by pressing the three dots in the top right corner and selecting 'Clone.'
`;

// Remember, users might have short attention span, large text returns confuses users.

function getSystemPrompt(template: string, imageSource: string): string {
  const imageSourceText = getImageSourceText(imageSource);
  let basePrompt = template ? systemPromptTranslation : drawToCodeSystemPrompt;

  basePrompt = basePrompt.replace("{{IMAGE_SOURCE}}", imageSourceText);

  const glowbomImagesInstructions =
    isGlowbomImagesSource(imageSource)
      ? "Using Glowbom Images means that you need to put every image prompt into a JavaScript variable at the end of the file. These prompts should be relevant to the code generation because post production uses them to generate images. Use the format img1 = 'glowbyimage:ADD_IMG_PROMPT_HERE'. You can add as many numbered image variables as needed."
      : "";

  // Generate the webpage code, but for Glowbom Images, do not set src in HTML img tags. Define prompts as JavaScript variables and assign them to image elements dynamically.
  basePrompt = basePrompt.replace(
    "{{GLOWBY_IMAGES_INSTRUCTIONS}}",
    glowbomImagesInstructions
  );

  return basePrompt;
}

export const chatWithAI = functions
  .runWith({ timeoutSeconds: 360 })
  .runWith({
    maxInstances: 3000,
  })
  .https.onRequest((request, response) => {
    corsHandler(request, response, async () => {
      try {
        if (!request.headers.authorization) {
          throw new Error("Unauthorized - No Authorization header provided");
        }
        // Extract message from request body
        const message = request.body.message || "No message provided";
        const previousMessages = request.body.previousMessages || [];
        const image = request.body.image;
        const groqKey = request.body.groq;
        const template = request.body.template;
        const model = request.body.model;
        const imageSource = request.body.imageSource || "Lorem Picsum"; // Default to Lorem Picsum if not provided

        if (image) {
          const userPrompt = message;
          const prompt = getSystemPrompt(template, imageSource);

          if (model === "r1") {
            const openAiResponseAndUsage = await callR1DrawToCodeApi(
              image,
              userPrompt,
              prompt,
              template,
              imageSource
            );

            // Send back the user's email, name, and subscription status
            response.send({
              message: message,
              aiResponse: openAiResponseAndUsage.aiResponse,
              tokenUsage: openAiResponseAndUsage.tokenUsage,
              cost: openAiResponseAndUsage.cost,
            });
          } else if (model === "r1-groq") {
            const openAiResponseAndUsage = await callR1GroqDrawToCodeApi(
              image,
              userPrompt,
              prompt,
              template,
              imageSource,
              groqKey
            );

            // Send back the user's email, name, and subscription status
            response.send({
              message: message,
              aiResponse: openAiResponseAndUsage.aiResponse,
              tokenUsage: openAiResponseAndUsage.tokenUsage,
              cost: openAiResponseAndUsage.cost,
            });
          }
        } else {
          // Assuming 'system' role initiates the conversation context if necessary
          const inputMessages = [
            { role: "system", content: defaultSystemPrompt },
            ...previousMessages,
            { role: "user", content: message },
          ];

          if (model === "r1") {
            // Call Anthropic API
            const openAiResponseAndUsage = await callR1Api(inputMessages);

            // Send back the user's email, name, and subscription status
            response.send({
              message: message,
              aiResponse: openAiResponseAndUsage.aiResponse,
              tokenUsage: openAiResponseAndUsage.tokenUsage,
              cost: openAiResponseAndUsage.cost,
            });
          } else if (model === "r1-groq") {
            // Call Anthropic API
            const openAiResponseAndUsage = await callR1GroqApi(
              inputMessages,
              groqKey
            );

            // Send back the user's email, name, and subscription status
            response.send({
              message: message,
              aiResponse: openAiResponseAndUsage.aiResponse,
              tokenUsage: openAiResponseAndUsage.tokenUsage,
              cost: openAiResponseAndUsage.cost,
            });
          }
        }
      } catch (error) {
        console.error(error);
        response
          .status(401)
          .send(
            "Unauthorized - Error verifying token or fetching subscription"
          );
      }
    });
  });

// R1

export async function callR1DrawToCodeApi(
  imageBase64: string,
  userPrompt: string,
  prompt: string,
  template: string,
  imageSource: string
): Promise<{ aiResponse: string; tokenUsage: any; cost: number }> {
  // System message
  const systemMessage =
    prompt +
    " Replace @tailwind placeholders with the Tailwind CSS CDN link to load the real framework.";

  // Use imageSource in the detailed task description
  let imageSourceText = getImageSourceText(imageSource);
  if (isGlowbomImagesSource(imageSource)) {
    imageSourceText +=
      " Ensure any declared image variables (like const img1 = ...) are assigned to matching <img id=\"img1\"> elements via JavaScript (e.g. document.getElementById('img1').src = img1)." +
      "Don't place glowbyimage: in <img src>; instead, leave it as a placeholder (e.g. 'about:blank') and set .src in JavaScript with the glowbyimage variable.";
  }
  const detailedTaskDescription = template
    ? template
    : `Turn this into a single HTML file using Tailwind. You should also show relevant real pictures from ${imageSourceText} website to make the generation more beautiful. Add working JavaScript for interactive features. The user describes this image as: ${userPrompt}`;

  try {
    // Step 1: Use Llama to describe the image
    const visionPayload = {
      model: "llama3.2-vision",
      messages: [
        {
          role: "user",
          content:
            "Describe this image using human language. If you see something in a foreign language, do not translate it to English. Make sure you describe all the elements and don't miss anything.",
          images: [imageBase64],
          max_tokens: 500,
        },
      ],
    };

    const visionResponse = await fetch("http://localhost:11434/api/chat", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(visionPayload),
    });

    //console.log("visionResponse ok ? = ", visionResponse.ok);
    //console.log("Vision payload:", JSON.stringify(visionPayload, null, 2));

    let imageDescription = "";

    if (visionResponse.ok) {
      // Handle streamed response from Ollama
      const readerVision = visionResponse.body?.getReader();
      const decoderVision = new TextDecoder();
      let chunkVision = "";

      //console.log("Starting to read vision response stream...");

      while (readerVision) {
        const { value, done } = await readerVision.read();
        //console.log("Stream read - done:", done, "value length:", value?.length);

        if (done) {
          //console.log("Stream complete");
          break;
        }

        chunkVision += decoderVision.decode(value, { stream: true });
        //console.log("Current chunk:", chunkVision);

        const lines = chunkVision.split("\n");
        chunkVision = lines.pop() || "";

        //console.log("Processing lines:", lines.length);

        for (const line of lines) {
          if (line.trim()) {
            try {
              //console.log("Parsing line:", line);
              const json = JSON.parse(line);
              //console.log("Parsed JSON:", json);
              if (json.message?.content) {
                imageDescription += json.message.content;
                //console.log("Current image description:", imageDescription);
              }
            } catch (e) {
              //console.log("Failed to parse JSON from line:", line);
              //console.error("Parse error:", e);
            }
          }
        }
      }
    }

    console.log("Final image description:", imageDescription);

    if (!imageDescription) {
      console.log("No image description generated");
    } else {
      console.log("Successfully got image description.");
    }

    // Step 2: Combine messages
    const inputMessages = [
      systemMessage, // System message is added raw (no special formatting)
      `<｜User｜>Image description: ${imageDescription}`,
      `<｜User｜>Detailed Task Description: ${detailedTaskDescription}`,
      `<｜User｜>Human: ${userPrompt}`,
    ];

    // Build prompt
    const prompt = inputMessages.join("\n") + "\n<｜Assistant｜>"; // Ensure the final Assistant tag

    console.log("prompt: ", prompt);

    // Step 3: Call R1 API
    const apiUrl = "http://localhost:11434/api/generate";
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "deepseek-r1:7b",
        prompt,
        max_tokens: 4096,
        temperature: 0.1,
      }), // deepseek-r1:7b or deepseek-r1:32b or deepseek-r1:14b
    });

    console.log("response status: ", response.status);

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `R1 API Request Failed. Status ${response.status}: ${errorText}`
      );
    }

    // Handle streamed response from R1
    const reader = response.body?.getReader();
    const decoder = new TextDecoder();
    let chunk = "";
    let aiResponse = "";

    while (reader) {
      const { value, done } = await reader.read();
      if (done) break;

      chunk += decoder.decode(value, { stream: true });
      const lines = chunk.split("\n");
      chunk = lines.pop() || "";

      for (const line of lines) {
        if (line.trim()) {
          const json = JSON.parse(line);
          aiResponse += json.response || "";
        }
      }
    }

    if (!aiResponse) {
      throw new Error("No valid response from R1 model");
    }

    // Step 4: Token usage and cost calculation
    const inputLen = prompt.length;
    const outputLen = aiResponse.length;
    const inputTokens = Math.ceil(inputLen / 4);
    const outputTokens = Math.ceil(outputLen / 4);
    const totalTokens = inputTokens + outputTokens;

    const costPerMillionTokens = 9.5;
    let cost = (totalTokens / 1_000_000) * costPerMillionTokens;

    const tokenUsage = 0;

    // Updated cost calculation using per thousand tokens pricing
    const costPerThousandTokens = 0.0105;

    if (tokenUsage) {
      const totalTokensCost = (tokenUsage / 1_000) * costPerThousandTokens;
      cost += totalTokensCost;
    }

    console.log("ai response: ", aiResponse);

    return {
      aiResponse,
      tokenUsage: {
        inputTokens,
        outputTokens,
        totalTokens,
        visionTokens: tokenUsage,
      },
      cost,
    };
  } catch (error: any) {
    console.error("Error:", error.message);
    if (error.response) {
      console.error("Error response data:", error.response.data);
      console.error("Error response status:", error.response.status);
      console.error("Error response headers:", error.response.headers);
    } else if (error.request) {
      console.error("No response received:", error.request);
    }

    throw new Error(
      "Failed to generate response from R1 draw-to-code pipeline"
    );
  }
}

export async function callR1Api(
  inputMessages: { role: string; content: string }[]
): Promise<{ aiResponse: string; tokenUsage: any; cost: number }> {
  // Ensure system message is included
  const systemMessage =
    inputMessages[0]?.role === "system"
      ? inputMessages[0]
      : { role: "system", content: "You are a helpful assistant." };
  const messages = [
    systemMessage,
    ...inputMessages.filter((m) => m.role !== "system"),
  ];

  // Ollama endpoint (local)
  const apiUrl = "http://localhost:11434/api/generate";

  try {
    const systemMessage =
      messages.find((m) => m.role === "system")?.content || "";

    const formatted = messages
      .filter((m) => m.role !== "system")
      .map((m, i, arr) => {
        const isLast = i === arr.length - 1;
        let result =
          m.role === "assistant"
            ? `<｜Assistant｜>${m.content}`
            : `<｜User｜>${m.content}`;
        if (m.role === "assistant" && !isLast) {
          result += "<｜end▁of▁sentence｜>";
        }
        return result;
      })
      .join("");

    // If the last message isn’t assistant, add <｜Assistant｜>
    const lastMsg = messages[messages.length - 1];
    const needsAssistantTag =
      lastMsg?.role !== "assistant" && lastMsg?.role !== "system";

    const prompt = [
      systemMessage,
      formatted,
      needsAssistantTag ? "<｜Assistant｜>" : "",
    ].join("");

    console.log("prompt: ", prompt);

    // Fetch request to Ollama's R1 model
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "deepseek-r1:7b", // // deepseek-r1:7b or deepseek-r1:32b or deepseek-r1:14b
        prompt,
        max_tokens: 500,
        temperature: 0.1,
        //stop: ["USER:", "ASSISTANT:", "SYSTEM:"],
      }),
    });
    console.log("response status: ", response.status);

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `API Request Failed. Status ${response.status}: ${errorText}`
      );
    }

    // Stream reader to process the response
    const reader = response.body?.getReader();
    const decoder = new TextDecoder();
    let chunk = "";
    let aiResponse = "";

    while (reader) {
      const { value, done } = await reader.read();
      if (done) break;

      // Decode the incoming data
      chunk += decoder.decode(value, { stream: true });

      // Process chunked data
      const lines = chunk.split("\n");
      chunk = lines.pop() || ""; // Save the partial chunk for the next loop

      for (const line of lines) {
        if (line.trim()) {
          const json = JSON.parse(line);
          aiResponse += json.response || "";
        }
      }
    }

    if (!aiResponse) {
      throw new Error("No valid response from R1 model");
    }

    // Calculate token usage
    const inputLen = messages.reduce((sum, m) => sum + m.content.length, 0);
    const outputLen = aiResponse.length;
    const inputTokens = Math.ceil(inputLen / 4);
    const outputTokens = Math.ceil(outputLen / 4);
    const totalTokens = inputTokens + outputTokens;

    // Calculate cost (adjust as needed)
    const costPerMillion = 9.5; // Example cost per million tokens
    const cost = (totalTokens / 1_000_000) * costPerMillion;

    return {
      aiResponse,
      tokenUsage: { inputTokens, outputTokens, totalTokens },
      cost,
    };
  } catch (error: any) {
    console.error("Error:", error.message);
    throw new Error("Failed to get response from local R1 model");
  }
}

// R1 Groq

export async function callR1GroqDrawToCodeApi(
  imageBase64: string,
  userPrompt: string,
  prompt: string,
  template: string,
  imageSource: string,
  groqKey: string
): Promise<{ aiResponse: string; tokenUsage: any; cost: number }> {
  const apiKey = groqKey; // || functions.config().groq.api_key;

  if (!apiKey || apiKey === "") {
    return {
      aiResponse:
        "Sorry, it seems the API key is missing or invalid. Please check your configuration and try again.",
      tokenUsage: {
        inputTokens: 0,
        outputTokens: 0,
        totalTokens: 0,
        visionTokens: {},
      },
      cost: 0,
    };
  }

  // System message
  const systemMessage = {
    role: "system",
    content:
      prompt +
      " Replace @tailwind placeholders with the Tailwind CSS CDN link to load the real framework.",
  };

  // Use imageSource in the detailed task description
  let imageSourceText = getImageSourceText(imageSource);
  if (isGlowbomImagesSource(imageSource)) {
    imageSourceText +=
      " Ensure any declared image variables (like const img1 = ...) are assigned to matching <img id=\"img1\"> elements via JavaScript (e.g. document.getElementById('img1').src = img1)." +
      "Don't place glowbyimage: in <img src>; instead, leave it as a placeholder (e.g. 'about:blank') and set .src in JavaScript with the glowbyimage variable." +
      "For every <img> element (including hero images), declare a corresponding JavaScript variable and assign its glowbyimage prompt as .src in the script.";
  }
  const detailedTaskDescription = template
    ? template
    : `Turn this into a single HTML file using Tailwind. You should also show relevant real pictures from ${imageSourceText} website to make the generation more beautiful. Add working JavaScript for interactive features. The user describes this image as: ${userPrompt}`;

  try {
    // Step 1: Use Gemini to describe the image
    const model = genAI.getGenerativeModel({
      model: "gemini-1.5-flash",
    });

    const image = {
      inlineData: {
        data: imageBase64,
        mimeType: "image/jpeg",
      },
    };

    let imageDescription = "Image description not available";
    try {
      const visionResult = await model.generateContent([
        "Describe this image using humam language. If you see something in the foreign language, do not translate it to english. Make sure you describe all the elements and don't miss anything.",
        image,
      ]);
      imageDescription = visionResult.response.text().trim();
      console.log("Image description:", imageDescription);
    } catch (error) {
      console.error("Failed to generate image description:", error);
    }
    console.log("Image description:", imageDescription);

    // Step 2: Combine messages
    const messages = [
      systemMessage,
      { role: "user", content: `Image description: ${imageDescription}` },
      {
        role: "user",
        content: `Detailed Task Description: ${detailedTaskDescription}`,
      },
      { role: "user", content: `Human: ${userPrompt}\nAssistant:` },
    ];

    // Build prompt
    console.log("Built prompt: ", messages);

    // Step 3: Call R1 API
    const apiUrl = "https://api.groq.com/openai/v1/chat/completions";
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        messages,
        model: "deepseek-r1-distill-llama-70b",
        temperature: 0.1,
        max_completion_tokens: 4096,
        top_p: 0.95,
        stream: true,
        stop: null,
      }),
    });

    console.log("response status: ", response.status);

    if (response.status === 429) {
      return {
        aiResponse: "We've hit Groq's limit. Please try again later.",
        tokenUsage: {
          inputTokens: 0,
          outputTokens: 0,
          totalTokens: 0,
          visionTokens: {},
        },
        cost: 0,
      };
    }

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `R1 API Request Failed. Status ${response.status}: ${errorText}`
      );
    }

    // Read the stream
    const reader = response.body?.getReader();
    const decoder = new TextDecoder();
    let chunk = "";
    let aiResponse = "";

    while (reader) {
      const { value, done } = await reader.read();
      if (done) break;

      chunk += decoder.decode(value, { stream: true });
      const lines = chunk.split("\n");
      chunk = lines.pop() || "";

      for (const line of lines) {
        const trimmed = line.trim();
        // We only process lines starting with "data:"
        if (!trimmed.startsWith("data:")) continue;

        const dataStr = trimmed.slice(5).trim();
        if (dataStr === "[DONE]") {
          // SSE done
          break;
        }

        try {
          const dataObj = JSON.parse(dataStr);
          const content = dataObj.choices?.[0]?.delta?.content;
          if (content) {
            aiResponse += content;
          }
        } catch (err) {
          console.error("JSON parse error:", err);
        }
      }
    }

    if (!aiResponse) {
      throw new Error("No valid response from R1 model");
    }

    // Step 4: Token usage and cost calculation
    const inputLen = prompt.length;
    const outputLen = aiResponse.length;
    const inputTokens = Math.ceil(inputLen / 4);
    const outputTokens = Math.ceil(outputLen / 4);
    const totalTokens = inputTokens + outputTokens;

    //const costPerMillionTokens = 9.5;
    let cost = 0; // (totalTokens / 1_000_000) * costPerMillionTokens;

    const tokenUsage = 0;

    console.log("ai response: ", aiResponse);

    return {
      aiResponse,
      tokenUsage: {
        inputTokens,
        outputTokens,
        totalTokens,
        visionTokens: tokenUsage,
      },
      cost,
    };
  } catch (error: any) {
    console.error("Error:", error.message);
    if (error.response) {
      console.error("Error response data:", error.response.data);
      console.error("Error response status:", error.response.status);
      console.error("Error response headers:", error.response.headers);
    } else if (error.request) {
      console.error("No response received:", error.request);
    }

    throw new Error(
      "Failed to generate response from R1 draw-to-code pipeline"
    );
  }
}

export async function callR1GroqApi(
  inputMessages: { role: string; content: string }[],
  groqKey: string
): Promise<{ aiResponse: string; tokenUsage: any; cost: number }> {
  const apiKey = groqKey; // || functions.config().groq.api_key;
  if (!apiKey || apiKey === "") {
    return {
      aiResponse:
        "Sorry, it seems the API key is missing or invalid. Please check your configuration and try again.",
      tokenUsage: {
        inputTokens: 0,
        outputTokens: 0,
        totalTokens: 0,
        visionTokens: {},
      },
      cost: 0,
    };
  }
  // Ensure system message is included
  const systemMessage =
    inputMessages[0]?.role === "system"
      ? inputMessages[0]
      : { role: "system", content: "You are a helpful assistant." };
  const messages = [
    systemMessage,
    ...inputMessages.filter((m) => m.role !== "system"),
  ];

  // Ollama endpoint (local)
  const apiUrl = "https://api.groq.com/openai/v1/chat/completions";

  console.log("messages: ", messages);

  try {
    // Fetch request to Ollama's R1 model
    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        messages,
        model: "deepseek-r1-distill-llama-70b",
        temperature: 0.6,
        max_completion_tokens: 4096,
        top_p: 0.95,
        stream: true,
        stop: null,
        //max_tokens: 500,
        //stop: ["USER:", "ASSISTANT:", "SYSTEM:"],
      }),
    });
    console.log("response status: ", response.status);

    if (response.status === 429) {
      return {
        aiResponse: "We've hit Groq's limit. Please try again later.",
        tokenUsage: {
          inputTokens: 0,
          outputTokens: 0,
          totalTokens: 0,
          visionTokens: {},
        },
        cost: 0,
      };
    }

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `API Request Failed. Status ${response.status}: ${errorText}`
      );
    }

    // Read the stream
    const reader = response.body?.getReader();
    const decoder = new TextDecoder();
    let chunk = "";
    let aiResponse = "";

    while (reader) {
      const { value, done } = await reader.read();
      if (done) break;

      chunk += decoder.decode(value, { stream: true });
      const lines = chunk.split("\n");
      chunk = lines.pop() || "";

      for (const line of lines) {
        const trimmed = line.trim();
        // We only process lines starting with "data:"
        if (!trimmed.startsWith("data:")) continue;

        const dataStr = trimmed.slice(5).trim();
        if (dataStr === "[DONE]") {
          // SSE done
          break;
        }

        try {
          const dataObj = JSON.parse(dataStr);
          const content = dataObj.choices?.[0]?.delta?.content;
          if (content) {
            aiResponse += content;
          }
        } catch (err) {
          console.error("JSON parse error:", err);
        }
      }
    }

    if (!aiResponse) {
      throw new Error("No valid response from R1 model");
    }

    // Calculate token usage
    const inputLen = messages.reduce((sum, m) => sum + m.content.length, 0);
    const outputLen = aiResponse.length;
    const inputTokens = Math.ceil(inputLen / 4);
    const outputTokens = Math.ceil(outputLen / 4);
    const totalTokens = inputTokens + outputTokens;

    // Calculate cost (adjust as needed)
    //const costPerMillion = 9.5; // Example cost per million tokens
    const cost = 0; //(totalTokens / 1_000_000) * costPerMillion;

    console.log(aiResponse);

    return {
      aiResponse,
      tokenUsage: { inputTokens, outputTokens, totalTokens },
      cost,
    };
  } catch (error: any) {
    console.error("Error:", error.message);
    throw new Error("Failed to get response from local R1 model");
  }
}
